### ISSUE TITLE
Transactions remains pending for a private testnet

### ISSUE THREAD

**Issue by DaveLomber** [ava-labs/avalanchego#1379]
**Describe the bug**

We are interested in running a private blockchain on top of avalanchego  platform code. With an empty state on the network, with just initial allocations.

We have 5 nodes setup for testnet. It's all provisioned via beacons. 
After DB cleanup, we can do one transaction in C chain, which is succeeded. All the further transactions remains pending

**To Reproduce**
- Have from 3 to 5 nodes run in a testnet mode for a private blockchain, with initial allocations
- Open wallet and send some coins from C to C chain. It works well.
- Send again some coins - the transactions remains pending and all further as well.

This is a screenshot from explorer which describes the issue:

<img width="1314" alt="Screenshot 2023-04-18 at 21 53 51" src="https://user-images.githubusercontent.com/39332586/232877127-f1c88e33-ca4a-4fcd-a898-a408e47a373d.png">

**Expected behavior**
All transactions work well

**Additional context**

Initially we have 3 nodes only. And the found this issue https://github.com/ava-labs/avalanchego/issues/225 where there is a suggestion to increase to 5. In our case it did not help - nothing changed.

**Comment by StephenButtolph** [comment]
Can you include the genesis config you are using along with the avalanchego config?

**Comment by DaveLomber** [comment]
@StephenButtolph please find all the configs:

**Beacons:**

```
case constants.FujiID:
  return []string{
    "140.xx.xx.xx:9651",
    "95.xx.xx.xx:9651",
    "104.xx.xx.xx:9651",
    "199.xx.xx.xx:9651",
    "192.xx.xx.xx:9651",
  }
		
...

case constants.FujiID:
  return []string{
    "NodeID-FGbQGVXhAX8v8yhkLuHpxFykkmx5skfqr",
    "NodeID-8a9Z7JPLZTZGrgxz1RG6JXPdC9dC5G8aB",
    "NodeID-Ltx3G2VNJdzZv7vuqy1vpKtoQnAWW19y4",
    "NodeID-Mm2DNdDNmckjs7aJ8Y2SgAq22Q73QYj1S",
    "NodeID-7Npphqf8thyrbukdgvGGZFvtf3Z2UWVSm",
  }
```

**Genesis:**

```
{
	"networkID": 5,
	"allocations": [
		{
			"ethAddr": "0x7bd20c8286d203615884d754ae89789b45c2a4bb",
			"avaxAddr": "X-fuji1yyza827hrwnngs5t306xkxyhpp7586gyr854c5",
			"initialAmount": 32000000000000000,
			"unlockSchedule": [
				{
					"amount": 40000000000000000,
					"locktime": 1681814000
				}
			]
		},
		{
			"ethAddr": "0x4585c0d89bf754bbc5139a9d96002ee080689477",
			"avaxAddr": "X-fuji150a7nrjv030zrnl787cfdzhv0g7jkh8masp3kz",
			"initialAmount": 32000000000000000,
			"unlockSchedule": [
				{
					"amount": 40000000000000000,
					"locktime": 1681814000
				}
			]
		}
	],
	"startTime": 1681812878,
	"initialStakeDuration": 31536000,
	"initialStakeDurationOffset": 54000,
	"initialStakedFunds": [
		"X-fuji1yyza827hrwnngs5t306xkxyhpp7586gyr854c5"
	],
	"initialStakers": [
		{
			"nodeID": "NodeID-FGbQGVXhAX8v8yhkLuHpxFykkmx5skfqr",
			"rewardAddress": "X-fuji1yyza827hrwnngs5t306xkxyhpp7586gyr854c5",
			"delegationFee": 1000000
		},
		{
			"nodeID": "NodeID-8a9Z7JPLZTZGrgxz1RG6JXPdC9dC5G8aB",
			"rewardAddress": "X-fuji1yyza827hrwnngs5t306xkxyhpp7586gyr854c5",
			"delegationFee": 1000000
		},
		{
			"nodeID": "NodeID-Ltx3G2VNJdzZv7vuqy1vpKtoQnAWW19y4",
			"rewardAddress": "X-fuji150a7nrjv030zrnl787cfdzhv0g7jkh8masp3kz",
			"delegationFee": 1000000
		},
		{
			"nodeID": "NodeID-Mm2DNdDNmckjs7aJ8Y2SgAq22Q73QYj1S",
			"rewardAddress": "X-fuji150a7nrjv030zrnl787cfdzhv0g7jkh8masp3kz",
			"delegationFee": 1000000
		},
		{
			"nodeID": "NodeID-7Npphqf8thyrbukdgvGGZFvtf3Z2UWVSm",
			"rewardAddress": "X-fuji150a7nrjv030zrnl787cfdzhv0g7jkh8masp3kz",
			"delegationFee": 1000000
		}
	],
	"cChainGenesis": "{\"config\":{\"chainId\":43113,\"homesteadBlock\":0,\"daoForkBlock\":0,\"daoForkSupport\":true,\"eip150Block\":0,\"eip150Hash\":\"0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0\",\"eip155Block\":0,\"eip158Block\":0,\"byzantiumBlock\":0,\"constantinopleBlock\":0,\"petersburgBlock\":0,\"istanbulBlock\":0,\"muirGlacierBlock\":0},\"nonce\":\"0x0\",\"timestamp\":\"0x0\",\"extraData\":\"0x00\",\"gasLimit\":\"0x7a1200\",\"difficulty\":\"0x0\",\"mixHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"coinbase\":\"0x0000000000000000000000000000000000000000\",\"alloc\":{\"7bd20c8286d203615884d754ae89789b45c2a4bb\":{\"balance\":\"0x3635C9ADC5DEA00000\"},\"4585c0d89bf754bbc5139a9d96002ee080689477\":{\"balance\":\"0x3635C9ADC5DEA00000\"}},\"number\":\"0x0\",\"gasUsed\":\"0x0\",\"parentHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}",
	"message": "hi mom"
}
```


**.avalanchego/configs/chains/C/config.json:**

```
{ 
 "coreth-admin-api-enabled": true, 
 "eth-apis": [ 
   "eth", 
   "eth-filter", 
   "net", 
   "web3", 
   "internal-eth", 
   "internal-blockchain", 
   "internal-transaction", 
   "internal-tx-pool", 
   "internal-account", 
   "internal-personal", 
   "debug-tracer", 
   "debug" 
 ] 
}
```


**.avalanchego/configs/node.json**


```
{ 
 "http-host": "", 
 "http-allowed-origins": "*, http://localhost:5000/, https://wallet-testnet.xx.xx",
 "public-ip": "104.207.131.83", 
 "network-id": "fuji", 
 "snow-sample-size": 5, 
 "snow-quorum-size": 3, 
 "snow-mixed-query-num-push-vdr": 3 
}
```

Also tried w.o
```
 "snow-sample-size": 5, 
 "snow-quorum-size": 3, 
 "snow-mixed-query-num-push-vdr": 3 
```
same results

**Comment by DaveLomber** [comment]
As an additional observation, at the time of 1st transaction made, we see the following errors in node logs:

```
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: ERROR[04-19|15:13:11.711] <C Chain> github.com/ava-labs/coreth/rpc/service.go:211: RPC method eth_estimateGas crashed: runtime error: invalid memory address or nil pointer dereference
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: goroutine 1942 [running]:
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/rpc.(*callback).call.func1()
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/rpc/service.go:210 +0x89
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: panic({0x15b94c0, 0x25836b0})
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /usr/local/go/src/runtime/panic.go:884 +0x213
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: math/big.(*Int).Cmp(0xc000ebf360?, 0x47570e?)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /usr/local/go/src/math/big/int.go:373 +0x25
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/core.(*StateTransition).preCheck(0xc002951980)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/core/state_transition.go:288 +0xc8e
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/core.(*StateTransition).TransitionDb(0xc002951980)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/core/state_transition.go:322 +0x5f
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/core.ApplyMessage(0x179d360?, {0x1b07c78?, 0xc001919ef0?}, 0x1b07c78?)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/core/state_transition.go:212 +0x2a
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/internal/ethapi.DoCall({0x1af80a0, 0xc001917b30}, {0x1b1cec8, 0xc000285b00}, {0xc00297a300, 0xc00297a318, 0xc001925e60, 0xc002952e40, 0x0, 0x0, ...}, ...)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/internal/ethapi/api.go:988 +0x6e5
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/internal/ethapi.DoEstimateGas.func1(0x3d3203)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/internal/ethapi/api.go:1158 +0x14f
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/internal/ethapi.DoEstimateGas({0x1af80a0, 0xc001917b30}, {0x1b1cec8?, 0xc000285b00?}, {0xc00297a300, 0xc00297a318, 0xc001925e60, 0xc002952e40, 0x0, 0x0, ...}, ...)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/internal/ethapi/api.go:1170 +0x97c
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/internal/ethapi.(*BlockChainAPI).EstimateGas(0xc0011bcdd0, {0x1af80a0, 0xc001917b30}, {0xc00297a300, 0xc00297a318, 0x0, 0xc002952e40, 0x0, 0x0, 0xc002952e60, ...}, ...)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/internal/ethapi/api.go:1211 +0x10d
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: reflect.Value.call({0xc0011d8cb0?, 0xc000015950?, 0x7f33d86f4758?}, {0x17e1e10, 0x4}, {0xc002a06000, 0x4, 0x0?})
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /usr/local/go/src/reflect/value.go:586 +0xb07
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: reflect.Value.Call({0xc0011d8cb0?, 0xc000015950?, 0x1?}, {0xc002a06000?, 0x2?, 0x16?})
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /usr/local/go/src/reflect/value.go:370 +0xbc
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/rpc.(*callback).call(0xc001228000, {0x1af80a0?, 0xc001917b30}, {0xc001925dd0, 0xf}, {0xc002975890, 0x2, 0x4dd797?})
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/rpc/service.go:216 +0x3c5
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/rpc.(*handler).runMethod(0xc0003fa820?, {0x1af80a0?, 0xc001917b30?}, 0xc0029448c0, 0x2?, {0xc002975890?, 0x0?, 0x40a825?})
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/rpc/handler.go:488 +0x45
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/rpc.(*handler).handleCall(0xc0016d9ea0, 0xc002921f20, 0xc0029448c0)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/rpc/handler.go:434 +0x239
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/rpc.(*handler).handleCallMsg(0xc0016d9ea0, 0xc002921f20, 0xc0029448c0)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/rpc/handler.go:395 +0x11d
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/rpc.(*handler).handleMsg.func1(0xc002921f20)
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/rpc/handler.go:167 +0x35
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: github.com/ava-labs/coreth/rpc.(*handler).startCallProc.func1()
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/rpc/handler.go:307 +0x1ba
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: created by github.com/ava-labs/coreth/rpc.(*handler).startCallProc
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:         /home/ku9n/go/pkg/mod/github.com/ava-labs/coreth@v0.11.9-rc.0/rpc/handler.go:311 +0xa5
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]:  
Apr 19 15:13:11 test-network-server-1 avalanchego[149715]: WARN [04-19|15:13:11.712] <C Chain> github.com/ava-labs/coreth/rpc/handler.go:403: Served eth_estimateGas conn=127.0.0.1:57950 reqid=3                execTime="516.396µs" procTime="517.406µs" totalTime="517.61µs"  err="method handler crashed"
Apr 19 15:13:12 test-network-server-1 avalanchego[149715]: INFO [04-19|15:13:12.980] <C Chain> github.com/ava-labs/coreth/internal/ethapi/api.go:1792: Submitted transaction hash=0x4278099f0a331bc357e26f2de203f74f4fecbce5afdde6a19e45a78bd03d8d2c from=0x7Bd20C8286d203615884d754Ae89789B45c2a4BB nonce=0 recipient=0x4585c0d89BF754BBC5139A9d96002EE080689477 value=10,000,000,000,000,000,000 type=0 gasFeeCap=281,250,000,000 gasTipCap=281,250,000,000 gasPrice=281,250,000,000
Apr 19 15:13:12 test-network-server-1 avalanchego[149715]: INFO [04-19|15:13:12.981] <C Chain> github.com/ava-labs/coreth/miner/worker.go:349: Commit new mining work number=1 hash=76e742..66b425 uncles=0 txs=1 gas=21000 fees=0.00590625 elapsed="500.308µs"
Apr 19 15:13:12 test-network-server-1 avalanchego[149715]: [04-19|15:13:12.982] INFO <C Chain> proposervm/pre_fork_block.go:172 built block {"blkID": "uNE9b8vcLb6MiBYyhnQuiEbsph9XreGpCjpFTDgHXXt1qdpoh", "height": 1, "parentTimestamp": "[01-01|00:00:00.000]"}
```

**Comment by DaveLomber** [comment]
As an additional observation which could help

When doing 2nd transaction, there is a suspicious log we found:

```
Apr 21 08:23:20 test-network-server-1 avalanchego[167910]: INFO [04-21|08:23:20.469] <C Chain> github.com/ava-labs/coreth/miner/worker.go:349: Commit new mining work number=2 hash=3e2ed9..353773 uncles=0 txs=1 g
as=21000 fees=0.00065625 elapsed="282.192µs" 
Apr 21 08:23:20 test-network-server-1 avalanchego[167910]: [04-21|08:23:20.470] INFO <C Chain> proposervm/pre_fork_block.go:223 built block {"blkID": "2jkJd6Td8i1ghMCA65KJfEHiLivkU76BkXstJ7yM983vW4czEM", "innerB
lkID": "UPP8kfKHPaXSNwr9MQy4FwpomMWuWHGhf27YbLEeb6Ue4fRwr", "height": 2, "parentTimestamp": "[04-21|08:02:22.000]", "blockTimestamp": "[04-21|08:23:20.000]"} 
Apr 21 08:23:20 test-network-server-1 avalanchego[167910]: [04-21|08:23:20.470] DEBUG <C Chain> snowman/transitive.go:883 block verification failed {"error": "block P-chain height larger than current P-chain hei
ght"} 
Apr 21 08:23:20 test-network-server-1 avalanchego[167910]: [04-21|08:23:20.470] DEBUG <C Chain> handler/handler.go:856 finished handling chan message {"messageOp": "notify"}
```

This one:
```
 block verification failed {"error": "block P-chain height larger than current P-chain hei
ght"} 
```

**Comment by DaveLomber** [comment]
It turned out, we need to set these values to 0
https://github.com/ava-labs/avalanchego/blob/master/version/constants.go#L76
so the it started to work well

@StephenButtolph please let me know if it worth documenting somewhere
