### ISSUE TITLE
pebbledb CI flake

### ISSUE THREAD

**Issue by joshua-kim** [ava-labs/avalanchego#2885]
Found test flake in CI:

```
-test.shuffle 1711670208533356353
unexpected fault address 0xffff4551a46a
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffff4551a46a pc=0x477830]

goroutine 19 [running]:
runtime.throw({0xe9f89b?, 0x1004506c8?})
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/panic.go:1077 +0x40 fp=0xc000373b80 sp=0xc000373b50 pc=0x43dca0
runtime.sigpanic()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/signal_unix.go:875 +0x22c fp=0xc000373be0 sp=0xc000373b80 pc=0x4571cc
runtime.memmove()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/memmove_arm64.s:65 +0x60 fp=0xc000373bf0 sp=0xc000373bf0 pc=0x477830
runtime.slicecopy(0xc0003a8018, 0x6?, 0xffff4551a46a, 0xc00028cb60?, 0xd9db60?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/slice.go:344 +0xa8 fp=0xc000373c40 sp=0xc000373bf0 pc=0x458ac8
slices.Clone[...](...)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/slices/slices.go:343
github.com/ava-labs/avalanchego/database/pebble.(*iter).Value(0xc0002a0af0)
	/opt/github-actions2/_work/avalanchego/avalanchego/database/pebble/iterator.go:106 +0x194 fp=0xc000373d10 sp=0xc000373c40 pc=0xc8be14
github.com/ava-labs/avalanchego/database.TestIteratorError(0xc00028cb60, {0x1004fd0, 0xc00033a270})
	/opt/github-actions2/_work/avalanchego/avalanchego/database/test_database.go:885 +0x368 fp=0xc000373e40 sp=0xc000373d10 pc=0xc7f7f8
github.com/ava-labs/avalanchego/database/pebble.TestInterface.func1(0x0?)
	/opt/github-actions2/_work/avalanchego/avalanchego/database/pebble/db_test.go:28 +0x6c fp=0xc000373e80 sp=0xc000373e40 pc=0xc8d06c
testing.tRunner(0xc00028cb60, 0xc00029e790)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1595 +0x1b4 fp=0xc000373fa0 sp=0xc000373e80 pc=0x5ee334
testing.(*T).Run.func1()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1648 +0x44 fp=0xc000373fd0 sp=0xc000373fa0 pc=0x5ef764
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc000373fd0 sp=0xc000373fd0 pc=0x476f34
created by testing.(*T).Run in goroutine 18
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1648 +0x5ec

goroutine 1 [chan receive]:
runtime.gopark(0xc00015f6c8?, 0x411f9c?, 0x70?, 0x78?, 0x0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:398 +0xc8 fp=0xc00015f640 sp=0xc00015f620 pc=0x440ab8
runtime.chanrecv(0xc000304070, 0xc00015f74f, 0x1)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/chan.go:583 +0x3b8 fp=0xc00015f6d0 sp=0xc00015f640 pc=0x40ab78
runtime.chanrecv1(0xe96340?, 0xd9d820?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/chan.go:442 +0x14 fp=0xc00015f700 sp=0xc00015f6d0 pc=0x40a784
testing.(*T).Run(0xc00028c820, {0xea3b64, 0xd}, 0xeea460)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1649 +0x608 fp=0xc00015f820 sp=0xc00015f700 pc=0x5ef568
testing.runTests.func1(0x0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:2054 +0x84 fp=0xc00015f880 sp=0xc00015f820 pc=0x5f28b4
testing.tRunner(0xc00028c820, 0xc00015fad8)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1595 +0x1b4 fp=0xc00015f9a0 sp=0xc00015f880 pc=0x5ee334
testing.runTests(0xc0002a4320?, {0x14c8160, 0x3, 0x3}, {0x2?, 0x419fc0?, 0x1529a40?})
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:2052 +0x6e8 fp=0xc00015fb00 sp=0xc00015f9a0 pc=0x5f2748
testing.(*M).Run(0xc0002a4320)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1925 +0x9f0 fp=0xc00015fe90 sp=0xc00015fb00 pc=0x5f0500
main.main()
	_testmain.go:93 +0x2b8 fp=0xc00015ff30 sp=0xc00015fe90 pc=0xc91cd8
runtime.main()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:267 +0x2bc fp=0xc00015ffd0 sp=0xc00015ff30 pc=0x44064c
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc00015ffd0 sp=0xc00015ffd0 pc=0x476f34

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x14d9280?, 0x0?, 0xa6?, 0x0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:398 +0xc8 fp=0xc000094790 sp=0xc000094770 pc=0x440ab8
runtime.goparkunlock(...)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:404
runtime.forcegchelper()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:322 +0xb8 fp=0xc0000947d0 sp=0xc000094790 pc=0x440918
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc0000947d0 sp=0xc0000947d0 pc=0x476f34
created by runtime.init.6 in goroutine 1
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:310 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:398 +0xc8 fp=0xc0000abf60 sp=0xc0000abf40 pc=0x440ab8
runtime.goparkunlock(...)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mgcsweep.go:280 +0xa0 fp=0xc0000abfb0 sp=0xc0000abf60 pc=0x42a720
runtime.gcenable.func1()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mgc.go:200 +0x28 fp=0xc0000abfd0 sp=0xc0000abfb0 pc=0x41f268
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc0000abfd0 sp=0xc0000abfd0 pc=0x476f34
created by runtime.gcenable in goroutine 1
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mgc.go:200 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000260e0?, 0xff5ae8?, 0x1?, 0x0?, 0xc0000031e0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:398 +0xc8 fp=0xc0000aaf50 sp=0xc0000aaf30 pc=0x440ab8
runtime.goparkunlock(...)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x1529b40)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mgcscavenge.go:425 +0x5c fp=0xc0000aaf80 sp=0xc0000aaf50 pc=0x42801c
runtime.bgscavenge(0x0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mgcscavenge.go:653 +0x44 fp=0xc0000aafb0 sp=0xc0000aaf80 pc=0x428534
runtime.gcenable.func2()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mgc.go:201 +0x28 fp=0xc0000aafd0 sp=0xc0000aafb0 pc=0x41f208
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc0000aafd0 sp=0xc0000aafd0 pc=0x476f34
created by runtime.gcenable in goroutine 1
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mgc.go:201 +0xac

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:398 +0xc8 fp=0xc0000a4d80 sp=0xc0000a4d60 pc=0x440ab8
runtime.runfinq()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mfinal.go:193 +0x12c fp=0xc0000a4fd0 sp=0xc0000a4d80 pc=0x41e31c
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc0000a4fd0 sp=0xc0000a4fd0 pc=0x476f34
created by runtime.createfing in goroutine 1
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/mfinal.go:163 +0x80

goroutine 18 [chan receive]:
runtime.gopark(0xc000284c58?, 0x411f9c?, 0x70?, 0x78?, 0x0?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:398 +0xc8 fp=0xc000284bd0 sp=0xc000284bb0 pc=0x440ab8
runtime.chanrecv(0xc0003040e0, 0xc000284cdf, 0x1)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/chan.go:583 +0x3b8 fp=0xc000284c60 sp=0xc000284bd0 pc=0x40ab78
runtime.chanrecv1(0xe96340?, 0xd9d820?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/chan.go:442 +0x14 fp=0xc000284c90 sp=0xc000284c60 pc=0x40a784
testing.(*T).Run(0xc00028c9c0, {0xea4051, 0xd}, 0xc00029e790)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1649 +0x608 fp=0xc000284db0 sp=0xc000284c90 pc=0x5ef568
github.com/ava-labs/avalanchego/database/pebble.TestInterface(0x0?)
	/opt/github-actions2/_work/avalanchego/avalanchego/database/pebble/db_test.go:26 +0x8c fp=0xc000284e80 sp=0xc000284db0 pc=0xc8ceec
testing.tRunner(0xc00028c9c0, 0xeea460)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1595 +0x1b4 fp=0xc000284fa0 sp=0xc000284e80 pc=0x5ee334
testing.(*T).Run.func1()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1648 +0x44 fp=0xc000284fd0 sp=0xc000284fa0 pc=0x5ef764
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc000284fd0 sp=0xc000284fd0 pc=0x476f34
created by testing.(*T).Run in goroutine 1
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/testing/testing.go:1648 +0x5ec

goroutine 52 [runnable]:
runtime.gopark(0xc000227fa8?, 0x2?, 0x50?, 0xe0?, 0xc000227e9c?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:398 +0xc8 fp=0xc000227cc0 sp=0xc000227ca0 pc=0x440ab8
runtime.selectgo(0xc000227fa8, 0xc000227e98, 0x0?, 0x0, 0x0?, 0x1)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/select.go:327 +0x694 fp=0xc000227df0 sp=0xc000227cc0 pc=0x452f64
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
	/home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/vfs/disk_health.go:474 +0x11c fp=0xc000227fd0 sp=0xc000227df0 pc=0x90b2ec
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc000227fd0 sp=0xc000227fd0 pc=0x476f34
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked in goroutine 19
	/home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/vfs/disk_health.go:468 +0xfc

goroutine 55 [runnable]:
runtime.gopark(0xc000229fa8?, 0x2?, 0x0?, 0xc0?, 0xc000229f0c?)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/proc.go:398 +0xc8 fp=0xc000229d70 sp=0xc000229d50 pc=0x440ab8
runtime.selectgo(0xc000229fa8, 0xc000229f08, 0x0?, 0x0, 0x0?, 0x1)
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/select.go:327 +0x694 fp=0xc000229ea0 sp=0xc000229d70 pc=0x452f64
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
	/home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/vfs/disk_health.go:148 +0x11c fp=0xc000229fd0 sp=0xc000229ea0 pc=0x9098ec
runtime.goexit()
	/opt/github-actions2/_work/_tool/go/1.21.8/arm64/src/runtime/asm_arm64.s:1197 +0x4 fp=0xc000229fd0 sp=0xc000229fd0 pc=0x476f34
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 19
	/home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/vfs/disk_health.go:143 +0xa4
FAIL	github.com/ava-labs/avalanchego/database/pebble	0.062s
```

**Comment by a1k0n** [comment]
IMO the test that's causing this has a somewhat unreasonable expectation w.r.t. avalanchego:

```
	// Call Next() and ensure that if the database is closed, the iterator
	// can still report the current contents.
	require.True(iterator.Next())
	require.NoError(db.Close())
	require.Equal(key1, iterator.Key())
	require.Equal(value1, iterator.Value())
```

@danlaine @StephenButtolph is that really needed? obviously, depending on db backend, it can require extra copies of everything on every database iteration. it's already gracefully shutting down before closing the DB as I understand it.

to fix this the pebble/iterator.go Next() function needs to make `nextKey` a clone of `it.iter.Key()`, which is again cloned by the iter's Key() method (to support key mutability? the interface comments don't say whether the returned result is supposed to be freely mutated).

**Comment by StephenButtolph** [comment]
> is that really needed?

There are at least a couple of reasons that it is currently needed:

1. If A VM doesn't guarantee that all DB operations have stopped after returning from `Shutdown`. I believe this can currently happen in the P-chain here: https://github.com/ava-labs/avalanchego/blob/d8af66306a3ec63ddecf16bbb522f979688d414a/vms/platformvm/vm.go#L236
2. If A VM times out during `Shutdown`. See: https://github.com/ava-labs/avalanchego/blob/d8af66306a3ec63ddecf16bbb522f979688d414a/snow/networking/router/chain_router.go#L374

Admittedly both of these are pretty jank (and we should remove them both imo).

(1) is done to avoid releasing the `ctx.Lock` which is implicitly held when calling `Shutdown`. ex: https://github.com/ava-labs/avalanchego/blob/d8af66306a3ec63ddecf16bbb522f979688d414a/snow/engine/snowman/transitive.go#L435-L438. The goal is to completely remove https://github.com/ava-labs/avalanchego/blob/d8af66306a3ec63ddecf16bbb522f979688d414a/snow/context.go#L45 entirely. But it's just a relatively complex change.

(2) was added so that a bug in a VM wouldn't block shutting down the full node. I think a reasonable alternative here would be to move this timeout into the `rpcchainvm` level and then hold invariant that any embedded VM must shutdown gracefully. Alternatively we just say that running a buggy VM can cause the node to behave sub-optimally.

There may be other instances where it's technically possible for the DB to be closed under an in-use iterator... But at the very least we'd need to do a pass over our usage of iterators to ensure we meet this invariant if we added it.

**Comment by a1k0n** [comment]
Wow, thanks for the thorough run-down. Yes, while doing some tests I've seen (for example) X chain fetching also time out while shutting down (I was having some truly abysmal leveldb performance on this machine), which then led to accessing a closed DB:
```
[05-06|12:26:25.274] WARN <X Chain> router/chain_router.go:374 timed out while shutting down {"error": "context deadline exceeded"}
[05-06|12:27:06.421] FATAL <X Chain> handler/handler.go:341 shutting down chain {"reason": "received an unexpected error", "error": "closed while processing sync message: ancestors from NodeID-CYdCC4uTyAmEHW2CNB6oivzBtzqJn55mS"}
```

Fair enough, thanks.
