### ISSUE TITLE
Avalanche c-chain panic

### ISSUE THREAD

**Issue by sosedoff** [ava-labs/avalanchego#632]
Caught a random panic while hitting the C chain RPC.

Trace:
```
INFO [12-02|00:43:39] api/info/service.go#145: Info: Peers called
INFO [12-02|00:43:41] api/info/service.go#145: Info: Peers called
INFO [12-02|00:43:43] api/info/service.go#145: Info: Peers called
INFO [12-02|00:43:45] api/info/service.go#145: Info: Peers called
INFO [12-02|00:43:46] api/info/service.go#145: Info: Peers called
INFO [12-02|00:43:47] api/info/service.go#145: Info: Peers called
INFO [12-02|00:43:49] api/info/service.go#145: Info: Peers called
INFO [12-02|00:45:23] api/info/service.go#110: Info: GetNetworkName called
INFO [12-02|00:46:47] api/info/service.go#110: Info: GetNetworkName called
INFO [12-02|00:46:50] api/info/service.go#145: Info: Peers called
INFO [12-02|00:46:50] api/info/service.go#71: Info: GetNodeVersion called
INFO [12-02|00:46:50] api/info/service.go#145: Info: Peers called
INFO [12-02|00:46:50] api/info/service.go#71: Info: GetNodeVersion called
INFO [12-02|00:46:50] api/info/service.go#145: Info: Peers called
INFO [12-02|00:46:50] api/info/service.go#145: Info: Peers called
INFO [12-02|00:47:01] api/info/service.go#145: Info: Peers called
INFO [12-02|00:47:10] api/info/service.go#145: Info: Peers called
INFO [12-02|00:47:20] api/info/service.go#145: Info: Peers called
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5d4bf0]

goroutine 3669129 [running]:
bufio.(*Writer).Available(...)
	/usr/local/go/src/bufio/bufio.go:624
bufio.(*Writer).Write(0x0, 0x1b642b8, 0x2, 0x2, 0x5b33, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:634 +0x70
net/http.(*chunkWriter).Write(0xc0151ffe00, 0xc0177fa000, 0x5b33, 0x6000, 0x750dc9, 0xc016ab52a8, 0x0)
	/usr/local/go/src/net/http/server.go:385 +0x151
bufio.(*Writer).Write(0xc0176eafc0, 0xc0177fa000, 0x5b33, 0x6000, 0xc01773c000, 0x5b69, 0x5b69)
	/usr/local/go/src/bufio/bufio.go:639 +0x13d
net/http.(*response).write(0xc0151ffdc0, 0x5b33, 0xc0177fa000, 0x5b33, 0x6000, 0x0, 0x0, 0x0, 0xc0075b1c50, 0xc01251da38)
	/usr/local/go/src/net/http/server.go:1607 +0x30a
net/http.(*response).Write(0xc0151ffdc0, 0xc0177fa000, 0x5b33, 0x6000, 0x415f1b, 0xc01251dac8, 0x29b5edc8)
	/usr/local/go/src/net/http/server.go:1565 +0x56
github.com/gorilla/handlers.(*responseLogger).Write(0xc005fa9c20, 0xc0177fa000, 0x5b33, 0x6000, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/gorilla/handlers@v1.4.2/handlers.go:59 +0x51
github.com/ava-labs/avalanchego/vms/rpcchainvm/ghttp/gresponsewriter.(*Server).Write(0xc005fa9f40, 0x15ddd80, 0xc00687ac30, 0xc016f4bbd0, 0xc005fa9f40, 0xc00687ac30, 0xc00b839ba0)
	/go/src/github.com/ava-labs/avalanchego/vms/rpcchainvm/ghttp/gresponsewriter/writer_server.go:49 +0x159
github.com/ava-labs/avalanchego/vms/rpcchainvm/ghttp/gresponsewriter/gresponsewriterproto._Writer_Write_Handler(0xedd280, 0xc005fa9f40, 0x15ddd80, 0xc00687ac30, 0xc0013edc20, 0x0, 0x15ddd80, 0xc00687ac30, 0xc01773c000, 0x5b69)
	/go/src/github.com/ava-labs/avalanchego/vms/rpcchainvm/ghttp/gresponsewriter/gresponsewriterproto/gresponsewriter.pb.go:561 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc016732680, 0x15e8f20, 0xc01901bc80, 0xc016f55700, 0xc01aef9ec0, 0x1c9d880, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc016732680, 0x15e8f20, 0xc01901bc80, 0xc016f55700, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xcc5
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc017cd6ca0, 0xc016732680, 0x15e8f20, 0xc01901bc80, 0xc016f55700)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
```

Running avalanche go 1.0.6 in docker container on osx big sur.
Im not sure if this is helpful.

**Comment by StephenButtolph** [comment]
Does this happen repeatably? I haven't been able to replicate the problem yet, but I am on a linux box.

**Comment by sosedoff** [comment]
Not yet, i just started testing 1.0.6 but i must say i havent seen any panics since i've started using avalanchego node locally. I'll provide more details if i hit this panic again.

**Comment by aaronbuchwald** [comment]
What API call on the C-Chain triggered the panic?

**Comment by sosedoff** [comment]
Hard to say, but from the log i provided the last entry was getting the list of peers. Im not sure if all requests are being logged though.

**Comment by sosedoff** [comment]
i think this is a totally random panic, have not seen anything like this so far.
