### ISSUE TITLE
ansible: OSError 26 Text file is busy installing plugins/evm

### ISSUE THREAD

**Issue by moreati** [ava-labs/avalanchego#904]
N.B. Please assign this issue to me. I'll be investigating and hope to provide a PR soon.

**Describe the bug**
Using `scripts/ansible/service_playbook.yml` to upgrade a running node to 1.5.2 I encountered the following

```
TASK [avalanche_install : Install support files] *******************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 26] Text file busy: b'/usr/local/lib/avalanchego/plugins/evm'
failed: [node1] (item=/usr/local/lib/avalanchego/plugins) => changed=false 
  ansible_loop_var: item
  item:
    src: avalanchego-v1.5.2/plugins
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib/python3.7/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_copy_payload_9xmde7eq/ansible_copy_payload.zip/ansible/modules/files/copy.py", line 790, in <module>
      File "/tmp/ansible_copy_payload_9xmde7eq/ansible_copy_payload.zip/ansible/modules/files/copy.py", line 753, in main
      File "/tmp/ansible_copy_payload_9xmde7eq/ansible_copy_payload.zip/ansible/modules/files/copy.py", line 417, in copy_diff_files
      File "/usr/lib/python3.7/shutil.py", line 121, in copyfile
        with open(dst, 'wb') as fdst:
    OSError: [Errno 26] Text file busy: b'/usr/local/lib/avalanchego/plugins/evm'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**To Reproduce**
`./service_playbook.yml -i myinventory` with the target already running an older version of AvalancheGo.

**Expected behavior**
...
```
TASK [avalanche_install : Remove outdated support files] ***********************
ok: [node1] => (item={'path': '/usr/local/lib/avalanchego/evm'})
ok: [node1] => (item={'path': '/usr/local/lib/avalanchego/avalanchego-preupgrade'})
ok: [node1] => (item={'path': '/usr/local/lib/avalanchego/avalanchego-latest'})

TASK [avalanche_install : Install support files] *******************************
changed: [node1] => (item=/usr/local/lib/avalanchego/plugins)

TASK [avalanche_staker : Create staking key] ***********************************
ok: [node1]
...
```

**Additional context**
As a workaround I manually stopped the avalanchego service, then reran the playbook.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by moreati** [comment]
Ahem, duplicate of https://github.com/ava-labs/avalanchego/issues/866, raised by me :roll_eyes: .
