### ISSUE TITLE
"panic: runtime error:  invalid memory address or nil pointer dereference" error at startup

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanchego#928]
**Describe the bug**
Starting up Avalanche may sometimes cause this error. Restarting the container fixes this issue, but this should never happen IMHO. 

NOTE: This happened when the node was having problems connecting to internet. And, please feel free to delete this if there are any security implications, but I don't think so.

**To Reproduce**
Start avalanchego in a Docker container.

**Expected behavior**
avalanchego should start normally.

**Logs**
```

     _____               .__                       .__
    /  _  \___  _______  |  | _____    ____   ____ |  |__   ____    ,_ o
   /  /_\  \  \/ /\__  \ |  | \__  \  /    \_/ ___\|  |  \_/ __ \   / //\,
  /    |    \   /  / __ \|  |__/ __ \|   |  \  \___|   Y  \  ___/    \>> |
  \____|__  /\_/  (____  /____(____  /___|  /\___  >___|  /\___  >    \\
          \/           \/          \/     \/     \/     \/     \/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xc4ab84]

goroutine 60 [running]:
github.com/ava-labs/avalanchego/node.(*Node).shutdown(0xc0001b4240)
        /build/node/node.go:1101 +0xa4
sync.(*Once).doSlow(0xc0001b4428, 0xd6e100)
        /usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/ava-labs/avalanchego/node.(*Node).Shutdown(0xc0001b4240, 0x407898)
        /build/node/node.go:1097 +0x94
github.com/ava-labs/avalanchego/app/process.(*App).Stop(0xc00019ea00)
        /build/app/process/process.go:181 +0x2a
github.com/ava-labs/avalanchego/app/entry.Run.func1({0x440985, 0xc000346630})
        /build/app/entry/runner.go:56 +0x1d
github.com/ava-labs/avalanchego/utils.HandleSignals.func1()
        /build/utils/signal.go:30 +0x48
created by github.com/ava-labs/avalanchego/utils.HandleSignals
        /build/utils/signal.go:28 +0x112
```

**Operating System**
Linux 3.10.108 x86_64 Braswell

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by aaronbuchwald** [comment]
I was able to reproduce a similar error by hitting Ctrl+C very quickly as the node starts up. There appears to be a race condition that can cause an ungraceful shutdown if the node has not finished initialization when it receives the command to shutdown. I just created a PR to resolve this issue, but am not sure it's actually the issue you're running into.

Are you hitting Ctrl+C or attempting to shut down the node in some way? If not, then I am probably reproducing a separate issue.

**Comment by ssg** [comment]
Yes, that's probably it. I didn't Ctrl+C the app, but I might have stopped (or restarted) Docker container at a point while it's in a restart loop which might have caused this.

**Comment by aaronbuchwald** [comment]
Thanks, and what version and/or commit of AvalancheGo are you running?

**Comment by ssg** [comment]
1.6.1

**Comment by StephenButtolph** [comment]
Thanks for bringing this up - this will be addressed in v1.6.2. There is a race condition where killing the node during initialization causes a panic.

**Comment by StephenButtolph** [comment]
This is resolved in #934.
